config/routes.rb
Rails.application.routes.draw do

  get 'movies/:id/actors/search' => 'actors#search'
  put 'movies/:movie_id/actors/:id' => 'actors#save'

  get 'sessions/new' => 'sessions#new', as: 'log_in'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy', as: 'log_out'

  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  get 'users' => 'users#index'
  root 'movies#index'

  resources :movies do
    resources :actors
  end

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  # has_and_belongs_to_many :movies
  has_many :actors_movies
  has_many :movies, :through => :actors_movies
  has_and_belongs_to_many :seedmovies

  def get_image
    if self.image_url.nil?
      base_url="http://private-e8bc0-themoviedb.apiary-proxy.com/3/search/person?api_key="
      key=ENV.fetch('TMDB_KEY')
      search = self.name.gsub!(" ","+") || self.name
      url = base_url + key + "&query=" + search
      results = HTTParty.get(url)
      profile_path=results["results"][0]["profile_path"]
      self.image_url = "http://image.tmdb.org/t/p/w500" + profile_path
      self.save
    end
    self.image_url
  end

end

app/models/actors_movie.rb
class ActorsMovie < ActiveRecord::Base
  belongs_to :actor
  belongs_to :movie

  validates :movie_id, uniqueness: {scope: :actor_id}
  validates :actor_id, uniqueness: {scope: :movie_id}

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  #has_and_belongs_to_many :actors
  belongs_to :user

  has_many :actors_movies
  has_many :actors, :through => :actors_movies

  def get_total_gross
    total = 0
    self.actors.each do |actor|
      total += actor.value
    end
    total
  end

  def ranking
    ranking = {}
    rank = 0
    arr = []

    Seedmovie.all.each do |movie|
      arr << movie
    end
    arr.sort! {|x, y| y[:gross] <=> x[:gross] }

    arr.each do |movie|
      if self.get_total_gross > movie.gross
        rank = arr.index(movie)+1
        break
      end
    end
    if rank == 0
      one_higher_title = ""
      one_higher_rank = ""
      one_lower_rank = ""
      one_lower_title = ""
    elsif rank == 1
      one_higher_title = ""
      one_higher_rank = ""
      one_lower_title = arr[rank].title
      one_lower_rank = "#" + (rank + 1).to_s
    else
      one_higher_title = arr[rank - 2].title
      one_higher_rank = "#" + (rank-1).to_s + ": "
      one_lower_title = arr[rank-1].title
      one_lower_rank = "#" + (rank + 1).to_s + ": "
    end

    #one_lower = arr[rank].title
    ranking = { :rank => "#" + (rank).to_s,
                :one_higher_title => one_higher_title,
                :one_lower_title => one_lower_title,
                :one_higher_rank => one_higher_rank,
                :one_lower_rank => one_lower_rank.to_s  }
  end

end

app/models/seedmovie.rb
class Seedmovie < ActiveRecord::Base
  #These are movies in the seedmovies table loaded in the seeds.rb.
  #This table of movies is necessary for calculating the value
  #of each actor.

  has_and_belongs_to_many :actors
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :movies
  has_secure_password

  validates :email,  presence: true, confirmation: true, uniqueness: true, email: true
  validates :password, length: {within: 4..20, too_short: "THE LENGTH IS TOO SHORT HOMIE", too_long: "THE LENGTH IS TOO LONG"}

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action:current_user

  def search
    actor = params[:search_term]
   # @results = Actor.where(name: params[:search_term])
   @results = Actor.where('name LIKE ?', "%#{ capitalize_phrase(actor) }%")
  end

  def save
    movie = Movie.find(params[:movie_id])
    actor = Actor.find(params[:id])
    movie.actors << actor rescue nil

    redirect_to "/movies/#{ movie.id }/edit"
  end

  def destroy
    movie = Movie.find(params[:movie_id])
    remove_actor = Actor.find(params[:id])
    movie.actors.delete(remove_actor)

    redirect_to "/movies/#{ movie.id }/edit"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to log_in_path if current_user == nil
  end

  def capitalize_phrase(phrase)
    phrase.split.map(&:capitalize).join(' ')
  end

  
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authorize


      def index
        @movies = current_user.movies

      end

      def create
        new_movie = Movie.create(movie_params)
        current_user.movies << new_movie

        redirect_to "/movies/#{ new_movie.id }/edit"
      end

      def new
        if (params[:gen_title])

            @title = generate_title
        else
          @title = ""
        end

      end

      def edit
        @movie = Movie.find(params[:id])
        if (params[:gen_title])

            @title = generate_title
        else
          @title = @movie.title
        end



      end

      def show
        @movie = Movie.find(params[:id])
      end

      def update
        edit_movie = Movie.find(params[:id])
        edit_movie.update(movie_params)

        redirect_to "/movies/#{ edit_movie.id }/edit"
      end

      def destroy
        Movie.delete(params[:id])

        redirect_to '/movies'

      end

      def generate_title
        adj_url="http://api.wordnik.com:80/v4/words.json/randomWords?hasDictionaryDef=false&includePartOfSpeech=adjective&minCorpusCount=0&maxCorpusCount=-1&minDictionaryCount=1&maxDictionaryCount=-1&minLength=5&maxLength=-1&limit=1&api_key="
        noun_url="http://api.wordnik.com:80/v4/words.json/randomWords?hasDictionaryDef=false&includePartOfSpeech=noun&minCorpusCount=0&maxCorpusCount=-1&minDictionaryCount=1&maxDictionaryCount=-1&minLength=5&maxLength=-1&limit=1&api_key="
        key=ENV.fetch('WORDNIK_KEY')

        adj_response = HTTParty.get(adj_url + key)
        adj = adj_response[0]["word"]
        noun_response = HTTParty.get(noun_url + key)
        noun = noun_response[0]["word"]

        capitalize_phrase(title = "The " + adj + " " + noun)


      end



      private
      def movie_params
        movie_params = params.require(:movie).permit(:title, :tagline)
      end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
      if params[:guest] then
          email = "guest@example.com"
          password = "password"
      else
          email = params[:email]
          password = params[:password]
      end
      user = User.find_by(email: email)

      if user && user.authenticate(password)
        session[:user_id] = user.id 
        redirect_to movies_path, notice: "Signed in as #{user.name}."
      else
        redirect_to log_in_path, alert: "Login failed."
      end
  end

  def destroy
      session[:user_id] = nil
      redirect_to log_in_path, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]

  def index
    @user = current_user
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render 'new'
    end

    # User.create(user_params)
    #redirect_to log_in_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email, :email_confirmation)
  end



end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/search.html.erb
<h1> pick an actor</h1>
<% @results.each do |actor| %>
<div class="nice_border">
  <%=actor.name%><form action="/movies/<%= params[:id] %>/actors/<%= actor.id %>" method="post"><%= token_tag %>
    <input type="hidden" name="_method" value="put">
    <button type="submit">You're hired!</button>
  </form>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinsl</title>
    <link href='http://fonts.googleapis.com/css?family=Poiret+One|Comfortaa:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/edit.html.erb
<%= render '/header.html.erb' %>
<div class="nice_border">
  <h3>Change title and tagline:</h3>
  <form action="/movies/<%= @movie.id %>" method="post">
    <%= token_tag %>
    <input type="hidden" name="_method" value="put">
    Movie Title:<input type="text" name="[movie]title" value="<%= @title %>">
     <a href="/movies/<%= @movie.id %>/edit?gen_title=true"><button>Write me a title!</button></a><br/>
    Tagline:<input type="text" name="[movie]tagline" value="<%= @movie.tagline %>">

    <button type="submit">Submit Changes</button>
  </form>
  <!--<a href="/movies/<%= @movie.id %>/edit?gen_title=true">Write me a title!</a> -->
</div><!--title_tag-->

<% if @movie.actors.count != 0 %>
  <div class="nice_border">
    <h3>Fire somebody.</h3>
      <% @movie.actors.each do |actor| %>
        <span class="actor"><%= actor.name %></span>
          <form action="/movies/<%= @movie.id %>/actors/<%= actor.id %>" method="post" class="delete_form">
            <%= token_tag %>
            <input type="hidden" name="_method" value="delete">
            <button type="submit" class="remove_button">You're fired!</button>
          </form><br />
      <% end %>
  </div><!--nice_border-->
<% end %>

<% if @movie.actors.count < 4 %>
<div class="nice_border">
  <h3>See who's available.</h3>
  <form action="/movies/<%= @movie.id %>/actors/search" method="get">
    <input type="text" name="search_term" placeholder="actor's name">
    <button type="submit">submit</button>
  </form>
</div><!--nice_border-->
<% end %>

  <div class="nice_border">
    <h3>Can the whole project.</h3>
  <form action="/movies/<%= @movie.id %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= token_tag %>
    <button type="submit">Can</button>
  </form>
</div><!--nice_border-->
<div class="nice_border">
  <a href="/movies"><button class="bottom_line">What's the bottom line?</button></a>
</div>

app/views/movies/index.html.erb
<%= render '/header.html.erb' %>
<h2 class="main_tagline">Be the movie mogul you always knew you could be</h3>
<div><span class="exec_producer"><%=current_user.name %>, executive producer</span><span class="log_out"><%= link_to "log out", log_out_path, method: :delete %></span>
<a href="/movies/new"><button class="create_movie">Create a movie</button></a></div>
<% @movies.each do |movie| %>
  <div class="sixteen columns movie clearfix">
    <div class="ten columns">
     <div class="title"><%= movie.title %></div>
     <div class="tagline"><%= movie.tagline %></div>

    <div class="actors clearfix">
      <% movie.actors.each do |actor| %>
      <div id="actor" class="two column"><%= actor.name %><br />
        <img src="<%= actor.get_image %>" class="actor_image">
      </div><!--actor-->
      <% end %>
    </div><!-- actors -->

  </div><!--seven column-->
    <!-- <div class="rightcol four column omega" id='rightcol' > -->
    <div id="rightcol" class="five column omega" >
      <div class="gross">$<%= number_with_delimiter(movie.get_total_gross) %></div>

      <div class="movie_rank_box">
        <div id="adjacent_ranking"><%= movie.ranking[:one_higher_rank] %> <%= movie.ranking[:one_higher_title] %></div>
        <div class="movie_rank"><%= movie.ranking[:rank] %></div>
        <div id="adjacent_ranking"><%= movie.ranking[:one_lower_rank] %> <%= movie.ranking[:one_lower_title] %></div>
        <div id="edit"><a href="/movies/<%= movie.id %>/edit"><button>Make Unreasonable Demands >></button></a></div>
      </div><!--movie_rank_box-->
    </div><!--rightcol-->
  </div><!--movie-->
<% end %>

app/views/movies/new.html.erb
<%= render '/header.html.erb' %>
<div class="nice_border">
  <h2>Pick a title and tagline.</h2>
  <form action="/movies" method="post">
    <%= token_tag %>
    <input type="text" name="[movie]title" placeholder="Movie Title" value="<%= @title %>">
    <input type="text" name="[movie]tagline" placeholder="Movie tagline">
    <button type="submit">Submit movie</button>
  </form>
  <a href="/movies/new?gen_title=true">Write me a title!</a>

</div>

app/views/movies/show.html.erb
<%= render '/header.html.erb' %>
<h1>Your Movie</h1>
<div class="title">
  <%= @movie.title %>
</div>
<div class="tagline">
  <%= @movie.tagline %>
</div>
<h3>The Cast</h3>
<ul>
  <% @movie.actors.each do |actor| %>
  <li><%= actor.name %>
    <form action="/movies/<%= @movie.id %>/actors/<%= actor.id %>" method="post">
      <%= token_tag %>
      <input type="hidden" name="_method" value="delete">
      <button type="submit">Remove</button>
    </form>
      </li>
  <% end %>
</ul>
<h3>Search for an actor</h3>
<form action="/movies/<%= @movie.id %>/actors/search" method="get">
  <input type="text" name="search_term" placeholder="actor's name">
  <button type="submit">submit</button>
</form>
<form action="/movies/<%= @movie.id %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <%= token_tag %>
       <button type="submit">Delete Movie</button>
<a href="/movies">Edit Movie</a>

app/views/shared/_header.html.erb
<h1 class="main_title"><%= link_to "Tinsl", root_path %></h1>

app/views/users/index.html.erb
<%= render '/header.html.erb' %>


<h2>Welcome</h2>

<% if current_user %>
  <p>
    <%= current_user.name %> ... is great
  </p>
  <%= link_to "Log-Out", log_out_path, method: :delete %>
<% else%>
  <%= link_to "Log-In", log_in_path %>
  <%= link_to "Sign-Up", users_new_path %>
<% end %>


<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.name %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= render '/header.html.erb' %>
<h1>Sign in to make film history</h1>
<% if @user.errors.any? %>
  <div class="errors">
    <p class="error-count">
      The form has <%= pluralize(@user.errors.count, "error") %>.
    </p>
    <ul class= "error-list">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="nice_border">
  <%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :email_confirmation %>
    <%= f.text_field :email_confirmation %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit %>
  <% end %>
</div>